### ISSUE TITLE
integration with nuxt

### ISSUE THREAD

**Issue by jankohlbach** [letmewin22/gl-html#1]
hey, saw your case study on awwwards and really interested in these libraries, the smoothscroll is working really nice and I love it's using the native scroll and not transforms, but I'm sadly not able to use this in my nuxt app :/
just get errors when I try in different ways, maybe you can help and guide me how I can properly integrate this in a nuxt app

**Comment by letmewin22** [comment]
Hi, thanks for your interest. Nuxt integration has its own peculiarities.
For example, in the attached file, what the initialization of smooth scroll
looks like in Nuxt. with the webgl library everything is the same

**Comment by jankohlbach** [comment]
thanks for the reply :)
think the file didn't really attach properly 😅 
but I have some progress (in the sense of less/other errors haha)

missed the async/await here:
```
async mounted () {
    const { initImages } = await import('~/assets/js/gl-images')
    if (window.scetch) {
      initImages()
    } else {
      window.addEventListener('scetch:created', initImages)
    }
}
```

but now somehow, in the Images extends Figure class I cannot access $el, the images seems to not be there ...

```
export default class Images extends Figure {
  textureLoaded = false

  constructor (scene, renderer, $el) {
    console.log(scene, renderer, $el)

    super(scene, renderer, $el)
```

gives me:
```
{el: img.image, scene: V, renderer: R, cover: {…}} undefined undefined
```

**Comment by letmewin22** [comment]
Hmm...you do everything right. Tell me more about this error, maybe then I can help.

**Comment by jankohlbach** [comment]
I looked how you did it here: https://github.com/letmewin22/terekhov/blob/e9f5056b0655e9c7dc781e53f3b357e54bca11eb/scripts/GL/Images/init.js
and tried to do the exact same thing, the canvas is there, there are no errors, but nothing more, I don't have the actual images on canvas
I feel like something in the Images class is wrong, because $el is undefined in there 🤔 
you can see here: https://github.com/jankohlbach/hotel1831-but-better/commit/4369fd5168b4ab70994bfbc5ba762ec483fee3d2

**Comment by letmewin22** [comment]
I'll try clone your repo and see what's wrong with code a bit latter

**Comment by letmewin22** [comment]
I looked at your code. There is a little complexity with how the elements get into the constructor :) If without details, then use the keyword "this" to refer to the elements. console.log(this.scene, this.renderer, this.$el) instead of console.log(scene, renderer, $el)

**Comment by jankohlbach** [comment]
thanks a lot for your fast help, I could get it working 😍 
for your information what I was doing wrong or what was missing:

https://github.com/jankohlbach/hotel1831-but-better/commit/daa128b745db97310845ddd336d63dc933b250f8#diff-5192a7e9ec23a66dcdfabc03f57e9711a786514dafd972afc640ef855364c7bfL27

https://github.com/jankohlbach/hotel1831-but-better/commit/daa128b745db97310845ddd336d63dc933b250f8#diff-7c035c3ad6ef46436ea64f1b74c17bbe3b422eafa5540acb72b9805efb0ef11aL4

now time to have fun with the shaders 🙌🏼
